// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PartsImport } from './routes/parts'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PartsIndexImport } from './routes/parts.index'
import { Route as PartsPartIdImport } from './routes/parts.$partId'

// Create/Update Routes

const PartsRoute = PartsImport.update({
  path: '/parts',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PartsIndexRoute = PartsIndexImport.update({
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)

const PartsPartIdRoute = PartsPartIdImport.update({
  path: '/$partId',
  getParentRoute: () => PartsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/parts': {
      preLoaderRoute: typeof PartsImport
      parentRoute: typeof rootRoute
    }
    '/parts/$partId': {
      preLoaderRoute: typeof PartsPartIdImport
      parentRoute: typeof PartsImport
    }
    '/parts/': {
      preLoaderRoute: typeof PartsIndexImport
      parentRoute: typeof PartsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  LoginRoute,
  PartsRoute.addChildren([PartsPartIdRoute, PartsIndexRoute]),
])
